In [1]:
!pip install nibabel numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 18.2 MB/s eta 0:00:00


In [1]:
import numpy as np
import nibabel as nib
import os

def create_and_read_nifti():
    """
    Demonstrates how to create and read a NIfTI file using nibabel.
    """
    filename = 'nifti_test.nii.gz'

    # --- Part 1: Create a simple NIfTI file ---
    print("--- Creating a new NIfTI file ---")
    
    # Create a 3D NumPy array to serve as our image data
    # This represents a simple brain-like image (e.g., a 10x10x10 cube of data)
    image_data = np.zeros((10, 10, 10), dtype=np.float32)
    image_data[2:8, 2:8, 2:8] = 1 # Create a cube of 'signal' in the center

    # Create a simple affine matrix
    # The affine matrix maps the voxel coordinates to real-world spatial coordinates.
    # We'll use a simple identity matrix for this demo.
    affine = np.diag([2, 2, 2, 1])

    # Create the NIfTI image object
    nifti_image = nib.Nifti1Image(image_data, affine)
    
    # Save the image to a compressed file
    nib.save(nifti_image, filename)
    print(f"File created successfully: '{filename}'\n")


    # --- Part 2: Read the NIfTI file ---
    print("--- Reading the created NIfTI file ---")

    # Load the NIfTI file from disk
    loaded_image = nib.load(filename)
    
    # Get the image data as a NumPy array
    loaded_data = loaded_image.get_fdata()
    
    # Print out some key information from the loaded file
    print("Loaded File Information:")
    print(f"  File name: {loaded_image.get_filename()}")
    print(f"  Header info: {loaded_image.header['srow_x']}") # Example of accessing header info
    print(f"  Shape of the image data: {loaded_data.shape}")
    print(f"  Data type: {loaded_data.dtype}")
    print(f"  Affine matrix:\n{loaded_image.affine}\n")
    
    # Clean up the created file
    #os.remove(filename)
    #print(f"Demo complete. File '{filename}' deleted.")

# Run the demonstration
if __name__ == "__main__":
    create_and_read_nifti()

--- Creating a new NIfTI file ---
File created successfully: 'nifti_test.nii.gz'

--- Reading the created NIfTI file ---
Loaded File Information:
  File name: nifti_test.nii.gz
  Header info: [2. 0. 0. 0.]
  Shape of the image data: (10, 10, 10)
  Data type: float64
  Affine matrix:
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 1.]]

